### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by aleksandar-stefanovic**

### CODE REVIEW

**Comment by donadigo** [comment]
Sorry, I pushed quite big commit and your branches has conflicts, please resolve them.
Also, couple of things about the branch itself:
1. Instead of "Settings settings", you should do "private Settings settings;"
2. I would choose IDESettings name for the settings class since, it doesn't become clear when also using GLib.Settings.
3. I don't know why the settings base is "org.ide", is it meant to be that?
4. Add spaces between the lines in "Gtk.Settings.get_default().set("gtk-application-prefer-dark-theme", true); to "Gtk.Settings.get_default ().set ("gtk-application-prefer-dark-theme", true);" for better reading the code.

**Comment by aleksandar-stefanovic** [comment]
1. Are you sure that it should be done like that? In Scratch, they use 

> public Settings settings;

So I just copy-pasted that... I mean, we could make it private, but then we'd have to create a settings instance in every class, which is inefficient. I'll set it to private...
1. Done.
2. Sorry, that was a mistake, fixed it.
3. Done. (sorry, I copy-pasted it from somewhere).

**Comment by donadigo** [comment]
Thanks for updating. If you want to make Settings accessible by any class, then use static instances in IDESettings class:
private static IDESettings instance;
public static IDESettings get_default () {
    if (settings == null) {
        instance = new IDESettings ();
   }

   return instance;
}

And then call get_default when you need the instance.

**Comment by donadigo** [comment]
Can we remove all that spaces after braces in IDESettings? This PR also shouldn't have added "add_window" line, "Apply black theme to the interface" change black here, to just dark.

**Comment by donadigo** [comment]
Are you done with changes? I wanted to merge it.

**Comment by aleksandar-stefanovic** [comment]
Yes :-)

**Comment by donadigo** [comment]
Hm, after a thought, it does compile, but it will fail to run because there is no schema installed.

Can you apply these changes?
- Add a "**add_subdirectory (schemas)**" in the main CMakeLists.txt file (in root of the directory)
- Add a CMakeLists.txt file in schemas directory and put in it:
  **include (GSettings)
  add_schema ("com.github.donadigo.elementary-ide.gschema.xml")**

**Comment by aleksandar-stefanovic** [comment]
Done, I think that you can accept the merge within a new branch ("settings", instead of "master"), so that you can continue adding your commits to it (if you find it easier to do it like that). I'm not 100% sure, though...

**Comment by donadigo** [comment]
You forgot newline after include (GSettings) and it fails to build the project.

**Pull request merged**
